dynamodb-toolbox/dynamodb-toolbox

README.md, __tests__/model-creation.unit.test.js, __tests__/models/simple-model.js, __tests__/parse.unit.test.js, __tests__/put.unit.test.js, index.js, package.json
=> Add delimiter option for composite sortKey generation

README.md
This was something I stubbed my toe on (obvious in retrospect!) so I thought it would be a good idea to point out to folks ahead of time.
Thanks for the excellent and thorough docs 💙
=> Fix typo and add info on indexing entityField

README.md
This small PR includes an example on how to update attributes. I hope this makes it easier for others to quickly understand how to use this method.
Let me know if another location is better or you want me to include some tests (iirc there are no tests that directly test for `Entity.update`.
=> Add an example for attribute updates

__tests__/expressionBuilder.unit.test.js, lib/expressionBuilder.js
=> Allow 0 in comparaison operators

src/classes/Entity.ts
This is a fix for #102.
Happy to add tests if required.
=> Support 0 in required number fields. Fixes #102

src/classes/Entity.ts
Support add zero: `{ key: { $add: 0 } }`
=> Support add zero

src/classes/Entity.ts
Fixes #224 by exporting the interface `ParsedAttributes`
=> fix(v0.4): ParsedAttributes ts error

src/__tests__/entity.update.unit.test.ts, src/classes/Entity/types.ts, src/classes/Table/types.ts
=> feat(types/entity-update): add prepend and append support

src/classes/Entity/Entity.ts
=> feat(entity/update/types): use UpdateCustomParams type

src/__tests__/table.query.unit.test.ts, src/__tests__/table.scan.unit.test.ts, src/classes/Table/Table.ts
=> test(table/query+scan): add coverage for hidden properties

src/index.ts
=> refactor: export InferEntityItem

jest.config.js, src/classes/Table/Table.ts
Small change to the jest config that I forgot to include in https://github.com/jeremydaly/dynamodb-toolbox/pull/317
My bad !
=> Improve test & build definition process

src/v1/item/typers/any/interface.ts, src/v1/item/typers/any/options.ts, src/v1/item/typers/common/interface.ts, src/v1/item/typers/common/options.ts, src/v1/item/typers/leaf/interface.ts, src/v1/item/typers/leaf/options.ts, src/v1/item/typers/list/interface.ts, src/v1/item/typers/list/options.ts, src/v1/item/typers/map/interface.ts, src/v1/item/typers/map/options.ts
Factorize some types for more simplicity.
=> Factorize item typers options and states

README.md
=> docs(README): add `Why single table design` section

src/__tests__/entity.update.unit.test.ts, src/classes/Entity/Entity.ts
=> fix(entity/update): resolve empty $set obj leading to invalid operation

src/__tests__/entity.update.unit.test.ts, src/classes/Entity/types.ts
=> fix(entity/update): resolve required attr type not inferred properly

.github/workflows/pull-request.yml, package-lock.json, package.json, src/__tests__/entity.update.unit.test.ts, src/__tests__/type-infering.unit.test.ts, src/classes/Entity/Entity.ts, src/classes/Entity/index.ts, src/classes/Entity/types.ts, src/classes/Table/types.ts, src/lib/parseEntity.ts, src/lib/validateTypes.ts
=> ci: add prettier check

src/__tests__/bootstrap.test.ts, src/__tests__/table-creation.unit.test.ts, src/classes/Table/Table.ts
=> fix: resolve error when translate config is empty

src/v1/operations/batch/batchWrite.ts, src/v1/operations/batch/batchWrite.unit.test.ts, src/v1/operations/batch/deleteItem/BatchDeleteItemParams.unit.test.ts, src/v1/operations/batch/putItem/BatchPutItemParams.unit.test.ts, src/v1/operations/deleteItem/command.ts, src/v1/operations/deleteItem/deleteItemParams/deleteItemParams.unit.test.ts, src/v1/operations/errors.ts, src/v1/operations/getItem/command.ts, src/v1/operations/getItem/getItemParams/getItemParams.unit.test.ts, src/v1/operations/putItem/command.ts, src/v1/operations/putItem/putItemParams/putItemParams.unit.test.ts, src/v1/operations/query/command.ts, src/v1/operations/query/queryParams/queryParams.unit.test.ts, src/v1/operations/scan/command.ts, src/v1/operations/scan/scanParams/scanParams.unit.test.ts, src/v1/operations/transactions/deleteItem/operation.ts, src/v1/operations/transactions/deleteItem/transactDeleteItemParams/transactDeleteItemParams.unit.test.ts, src/v1/operations/transactions/putItem/operation.ts, src/v1/operations/transactions/putItem/transactPutItemParams/transactPutItemParams.unit.test.ts, src/v1/operations/transactions/updateItem/operation.ts, src/v1/operations/transactions/updateItem/transactUpdateItemParams/transactUpdateItemParams.unit.test.ts, src/v1/operations/updateItem/command.ts, src/v1/operations/updateItem/updateItemParams/updateItemParams.unit.test.ts, src/v1/table/class.ts
related to https://github.com/jeremydaly/dynamodb-toolbox/projects/2#card-91242915
=> feat : make document client optional in tables

src/v1/index.ts, src/v1/operations/transactions/conditionCheck/conditionCheckParams/conditionCheckParams.ts, src/v1/operations/transactions/conditionCheck/conditionCheckParams/conditionCheckParams.unit.test.ts, src/v1/operations/transactions/conditionCheck/conditionCheckParams/index.ts, src/v1/operations/transactions/conditionCheck/conditionCheckParams/parseConditionCheckOptions.ts, src/v1/operations/transactions/conditionCheck/index.ts, src/v1/operations/transactions/conditionCheck/operation.ts, src/v1/operations/transactions/index.ts, src/v1/operations/transactions/transactWriteItems/transactWriteItems.unit.test.ts
=> Feat/add ConditionCheck for transactions

src/__tests__/normalizeData.unit.test.ts, src/__tests__/type-infering.unit.test.ts, src/lib/normalizeData.ts
=> fix: remove attributes that depend on attributes that can't be resolved

src/__tests__/entity.get.unit.test.ts, src/classes/Entity/Entity.ts, src/lib/normalizeData.ts
=> fix(Entity/get): don't fail when missing non partition required properties

docs/docs/3-entities/3-actions/3-update-item/index.md, docs/docs/4-schemas/8-binary/index.md, src/attributes/primitive/types.ts, src/attributes/primitive/types.type-test.ts, src/entity/actions/transactUpdate/updateTransaction.unit.test.ts, src/entity/actions/transactWrite/execute.unit.test.ts, src/entity/actions/update/updateItemParams/updateItemParams.unit.test.ts, src/schema/actions/parseCondition/condition.type.test.ts, src/table/actions/parsePrimaryKey/primaryKeyParser.ts, src/table/types/keyType.ts, src/utils/validation/isBinary.ts, src/utils/validation/isBinary.unit.test.ts, src/utils/validation/isPrimitive.ts, src/utils/validation/isPrimitive.unit.test.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/736
=> use uin8arrays instead of buffers for binaries

docs/docs/3-entities/2-internal-attributes/index.md, docs/docs/6-v0/9-migration-guide/index.md, src/entity/entity.ts, src/entity/utils/addInternalAttributes/addInternalAttributes.ts, src/entity/utils/addInternalAttributes/addInternalAttributes.unit.test.ts, src/entity/utils/addInternalAttributes/types.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/821
=> add entityAttributeHidden option to entity constructor (true by default)

tsconfig.esm.json
=> fix(esm-tsconfig): emit helpers to allow usage of decorator

docs/docs/2-tables/1-usage/index.md, src/table/actions/query/queryParams/queryParams.unit.test.ts, src/table/actions/query/types.ts, src/table/table.ts, src/table/types/indexes.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/834
=> enable GSIs without sort keys

docs/docs/2-tables/2-actions/2-query/index.md, docs/docs/3-entities/3-actions/17-parse-condition/index.md, src/schema/actions/parseCondition/index.ts, src/schema/actions/parseCondition/parseCondition/comparison/types.ts, src/table/actions/query/queryParams/queryParams.unit.test.ts, src/table/actions/query/types.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/856
=> enable eq conditions in ranges

src/schema/actions/utils/appendAttributePath.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/862
=> accept hyphens in attributePaths

.github/workflows/codeql.yml, .github/workflows/deploy-docs.yml, .github/workflows/draft-or-update-next-release.yml, .github/workflows/publish.yml, .github/workflows/pull-request.yml, src/index.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/877
=> export tableAction and entityAction from main entrypoint

src/entity/actions/update/updateItemParams/updateItemParams.unit.test.ts, src/utils/cloneDeep.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/881
=> fix bug with cloneDeep

.eslintrc.json, package-lock.json, package.json, src/entity/utils/doesSchemaValidateTableSchema.unit.test.ts, src/schema/actions/fromJSON/schema.unit.test.ts, src/schema/actions/jsonize/jsonizeAttribute/primitive.unit.test.ts, src/table/actions/spy/spy.ts, src/table/actions/spy/spy.type.test.ts, vitest.config.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/899
=> fix: enforce extensions in imports

README.md, package.json, src/entity/actions/put/putItemParams/putItemParams.unit.test.ts, src/entity/actions/transactPut/putTransaction.unit.test.ts, src/options/rejectExtraOptions.ts, src/schema/actions/parse/primitive.type.test.ts, src/table/actions/query/queryParams/parseQuery.ts
=> fix: typos

src/entity/actions/parse/entityParser.ts, src/entity/actions/parse/index.ts, src/entity/actions/put/putItemCommand.ts, src/entity/actions/put/putItemParams/putItemParams.ts, src/entity/actions/put/types.ts, src/entity/actions/transactPut/putTransaction.ts, src/entity/actions/transactUpdate/updateTransaction.ts, src/entity/actions/transactWrite/execute.unit.test.ts, src/entity/actions/update/updateItemParams/updateItemParams.ts, src/entity/actions/updateAttributes/updateAttributesParams/updateAttributesParams.ts, src/index.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/933
=> fix bug in put item type mismatch

src/schema/actions/format/anyOf.ts, src/schema/actions/format/list.ts, src/schema/actions/format/map.ts, src/schema/actions/format/record.ts, src/schema/actions/format/schema.ts, src/schema/actions/format/set.ts, src/schema/actions/format/types.ts, src/schema/actions/format/utils.ts, src/schema/actions/format/utils.unit.test.ts, src/schema/actions/parseCondition/parseCondition/parseCondition.unit.test.ts, src/schema/actions/parsePaths/pathParser.unit.test.ts, src/schema/actions/parsePaths/paths.ts, src/schema/actions/parsePaths/paths.type.test.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/928
=> fix: bug when formatting special chars

src/transformers/prefix.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/943
=> rework prefix export

docs/docs/1-getting-started/3-usage/index.md, docs/docs/2-tables/2-actions/1-scan/index.md, docs/docs/2-tables/2-actions/2-query/index.md, docs/docs/2-tables/2-actions/3-deletePartition/index.md, docs/docs/2-tables/2-actions/5-batch-get/index.md, docs/docs/2-tables/2-actions/6-batch-write/index.md, docs/docs/3-entities/4-actions/1-get-item/index.md, docs/docs/3-entities/4-actions/10-transactions/index.md, docs/docs/3-entities/4-actions/11-transact-get/index.md, docs/docs/3-entities/4-actions/2-put-item/index.md, docs/docs/3-entities/4-actions/3-update-item/index.md, docs/docs/3-entities/4-actions/5-delete-item/index.md, docs/docs/4-schemas/1-usage/index.md, src/entity/actions/delete/deleteItemCommand.ts, src/entity/actions/get/getItemCommand.ts, src/entity/actions/put/putItemCommand.ts, src/entity/actions/transactGet/execute.ts, src/entity/actions/transactWrite/execute.ts, src/entity/actions/update/updateItemCommand.ts, src/entity/actions/updateAttributes/updateAttributesCommand.ts, src/entity/entity.ts, src/table/actions/batchGet/execute.ts, src/table/actions/batchWrite/execute.ts, src/table/actions/deletePartition/deletePartitionCommand.ts, src/table/actions/query/queryCommand.ts, src/table/actions/scan/scanCommand.ts, src/table/table.ts, src/types/documentClientOptions.ts
Closes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/984
=> enable passing document client options to send methods

src/table/index.ts
Closes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/997
=> export key type

docs/docs/2-tables/2-actions/1-scan/index.md, docs/docs/2-tables/2-actions/2-query/index.md, src/schema/actions/utils/appendAttributePath.ts, src/table/actions/query/options.ts, src/table/actions/query/queryParams/queryParams.ts, src/table/actions/query/queryParams/queryParams.unit.test.ts, src/table/actions/scan/options.ts, src/table/actions/scan/scanParams/scanParams.ts, src/table/actions/scan/scanParams/scanParams.unit.test.ts
Closes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/991
=> enable passing any filter to queries and scans (without entities)

src/entity/actions/transactGet/execute.ts, src/entity/actions/transactWrite/execute.ts, src/table/actions/batchGet/execute.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/1008
=> fix: small type bug

src/table/actions/query/queryCommand.ts, src/table/actions/query/queryCommand.unit.test.ts, src/table/actions/scan/scanCommand.ts, src/table/actions/scan/scanCommand.unit.test.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/1019
=> improve query and scan behaviors when entityAttrFilter is false

src/options/consistent.ts, src/table/actions/deletePartition/options.ts, src/table/actions/indexes.ts, src/table/actions/query/options.ts, src/table/actions/query/queryCommand.ts, src/table/actions/query/queryCommand.unit.test.ts, src/table/actions/query/queryParams/queryParams.ts, src/table/actions/query/queryParams/queryParams.unit.test.ts, src/table/actions/scan/options.ts, src/table/actions/scan/scanParams/scanParams.ts, src/table/actions/scan/scanParams/scanParams.unit.test.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/1051
=> enable consistent reads on local secondary indexes

docs/docs/3-entities/2-internal-attributes/index.md
@ThomasAribart I added this example following our discussion in #1045. Let me know if you want me to make any changes! 
Thanks
=> Add example referencing timestamp attributes

docs/docs/2-tables/2-actions/2-query/index.md, src/schema/actions/parseCondition/parseCondition/logicalCombination/parseCondition.ts, src/schema/actions/parseCondition/parseCondition/logicalCombination/parseCondition.unit.test.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/1073
=> fix: bug in logical condition combinations

docs/docs/3-entities/2-internal-attributes/index.md
Document the correct way to config timestamps from a variable, as explained in https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/1071#issuecomment-2646150948
=> Documentation timestamp options as const

src/schema/actions/utils/appendAttributePath.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/1078
=> fix: include more special chars in path regex

src/table/actions/batchGet/batchGetCommand.ts, src/table/actions/batchGet/execute.ts, src/table/actions/batchGet/index.ts, src/table/actions/batchWrite/batchWriteCommand.ts, src/table/actions/batchWrite/index.ts, src/table/actions/repository/repository.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/1093
=> fix bug in table repository type

docs/docs/4-schemas/18-transformers/1-usage.md
V2 docs for transformers still used format and parse, updated to use encode and decode
=> update transformer docs for v2

src/table/actions/deletePartition/deletePartitionCommand.ts, src/table/actions/query/options.ts, src/table/actions/query/queryCommand.ts, src/table/actions/query/queryCommand.unit.test.ts, src/table/actions/query/queryParams/errors.ts, src/table/actions/query/queryParams/queryParams.ts
Closes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/1124
=> remove $entity symbol from query results by default

src/table/actions/scan/scanCommand.ts
Was noticing some weird logging in my production application.  Found out where it was coming from ;)
=> remove console log statements

src/schema/anyOf/constants.ts, src/schema/anyOf/schema.ts, src/schema/anyOf/schema_.unit.test.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/1202
=> fix bug when using discriminators

src/entity/actions/accessPattern/accessPattern.unit.test.ts, src/table/actions/accessPattern/accessPattern.unit.test.ts, src/table/actions/query/options.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/1209
=> fix type bug following the introduction of access pattern context options

.github/workflows/pull-request.yml, docs/docs/4-schemas/17-actions/5-zod-schemer.md, package-lock.json, package.json, src/table/actions/scan/scanParams/scanParams.unit.test.ts
Fixes https://github.com/dynamodb-toolbox/dynamodb-toolbox/issues/1212
=> fix small docs typo
