- __tests__/expressionBuilder.unit.test.js
- lib/expressionBuilder.js
Currently this won't get passed to dynamo
filters: [{ attr: 'evs', eq: false }]
So, this changes the builder to be "did you pass it to me?"
fixes #41
> support false/empty string for eq

- __tests__/formatItem.unit.test.js
- lib/formatItem.js
Fixes #50 
Looking at the code I figured this was a bug, since there were guards for everything else.
PS. Thanks for this library, truly makes single table design approachable 🥇
> Allow attributes not specified in entity to be passed through

- .eslintrc.json
- __tests__/lib/getKey.unit.test.js
- lib/getKey.js
When I was experimenting with the toolbox my data model used the sk for widget versions where version 0 was the master version. getKey complained that sk was required, even though number 0 is allowed for sort keys. The problem in the getKey function was that it was expecting non falsy keys. So I wrote some specs and fixed the getKey function.
> Getkey handling falsy keys

- src/classes/Table.ts
Fixes #107 
Description:
* Adds number support to `queryOptions` interface
> fix: Fixing queryOptions interface to allow number comparisons

- src/classes/Entity.ts
In regards to https://github.com/jeremydaly/dynamodb-toolbox/issues/127
Excerpt from that issue:
> When I try:
```
Entity.putTransaction({ something: null })
```
I get the following TypeScript error:
> TS2322: Type 'null' is not assignable to type 'string | number | boolean | { [key: string]: SchemaType; } | SchemaType[] | undefined'.
Shouldn't `null` be a valid attribute value to pass to an entity, so long as it is not the PK or SK?
Proposed change to `Entity.ts` (also exporting `SchemaType` to be used directly in projects:
```
export type SchemaType =
| string
| number
| boolean
| { [key: string]: SchemaType }
| SchemaType[]
| null
```
> added null to SchemaType; exported SchemaType

- src/__tests__/entity.put.unit.test.ts
- src/classes/Entity.ts
Fix for https://github.com/jeremydaly/dynamodb-toolbox/issues/154
`required: true` is not accepting `false` and `0` values being passed into an Entity put.
> Fix required check not accepting 0 and false

- src/__tests__/entity.update.unit.test.ts
- src/classes/Entity.ts
When a `number`, `set`, `list` or `map` attribute value is `undefined`, an error is thrown:
`TypeError: Cannot read property '$add' of undefined`
This PR fixes this issue.
> fix undefined errors with $add, $remove, etc

- src/__tests__/entity.update.unit.test.ts
- src/__tests__/table.entities.unit.test.ts
- src/classes/Entity.ts
Hello and thanks for this wonderful project !
I was experimenting on the `v0.4` branch but the type inference did not work on entities with a GSI.
I think the fix enables that, but I don't completely understand how it breaks the tests :/
> types: support GSIs in type inference

- src/__tests__/entity.delete.unit.test.ts
- src/__tests__/entity.get.unit.test.ts
- src/__tests__/entity.utils.unit.test.ts
- src/__tests__/parseMapping.unit.test.ts
- src/__tests__/type-infering.unit.test.ts
- src/classes/Entity.ts
- src/classes/Table.ts
- src/lib/parseEntity.ts
- src/lib/parseMapping.ts
This PR implements support for `execute` and `parse` options in entities inferred types for `get`, `put`, `delete` and `update` methods, both for entity definitions and method options.
```
const regularEntity = new Entity({ ... })
const entityNoExecute = new Entity({
...
autoExecute: false
})
const params = await regularEntity({ ... }, { execute: false })
// => DocumentClient.GetItemInput
const params = await entityNoExecute({ ... })
// => DocumentClient.GetItemInput
const entityNoParse = new Entity({
...
autoParse: false
})
const output = await regularEntity({ ... }, { parse: false })
// => DocumentClient.GetItemOutput
const output = await entityNoParse({ ... })
// => DocumentClient.GetItemOutput
```
> Support execute and parse options in inferred types

- src/__tests__/entity.delete.unit.test.ts
- src/__tests__/entity.get.unit.test.ts
- src/__tests__/entity.utils.unit.test.ts
- src/__tests__/parseMapping.unit.test.ts
- src/__tests__/type-infering.unit.test.ts
- src/classes/Entity.ts
- src/classes/Table.ts
- src/index.ts
- src/lib/expressionBuilder.ts
- src/lib/parseEntity.ts
- src/lib/parseEntityAttributes.ts
- src/lib/parseMapping.ts
- src/lib/projectionBuilder.ts
Sometimes it can be useful to dynamically set an entity operation options. For instance:
```
const queryOptions = {};
if (!isSuperadmin(user)) {
queryOptions.beginsWith = 'USER'
}
const { Item } = await myEntity.query(pk, { attributes: ['name', 'age'], ...queryOptions })
```
Sadly, in TS this will throw an error, as `getOptions` is typed as `{}` by default. Using a non-generic `GetOptions` type will also throw an error because the entity attribute names are hardly typed now, and `string` will not be assignable to either the `attributes` or `conditions` options.
This PR proposes to solve this problem by exposing `GetOptions`, `PutOptions`, `DeleteOptions`, `UpdateOptions` & `QueryOptions` utility types:
```
import type { QueryOptions } from 'dynamodb-toolbox'
const queryOptions: …
```
> Export `GetOptions`, `PutOptions`, `DeleteOptions`, `UpdateOptions` & `QueryOptions` utility types

- src/__tests__/entity.delete.unit.test.ts
- src/__tests__/entity.get.unit.test.ts
- src/__tests__/entity.utils.unit.test.ts
- src/__tests__/parseMapping.unit.test.ts
- src/__tests__/type-infering.unit.test.ts
- src/classes/Entity.ts
- src/classes/Table.ts
- src/lib/parseEntity.ts
- src/lib/parseMapping.ts
This PR adds support for `timestamp` option in inferred types:
```typescript
const regularEntity = new Entity({
name: entityName,
attributes: {
pk: { type: 'string', partitionKey: true },
},
table: tableWithoutSK
} as const)
const { Item } = await regularEntity.get({ pk: 'pk' })
type RegularItem = typeof Item
// => { entity: string, created: string, modified: string, pk: string }
const entNoTimestamps = new Entity({
name: entityName,
timestamps: false,
attributes: {
pk: { type: 'string', partitionKey: true },
},
table: tableWithoutSK
} as const)
const { Item } = await entNoTimestamps.get({ pk: 'pk' })
type NoTimestampItem = typeof Item
// => { entity: string, pk: string } 🙌
```
> Support `timestamp` option in inferred types

- src/classes/Entity.ts
I'm pretty sure this type is wrong, looking at how `transform` is used by [`utils/transformAttr`](https://github.com/jeremydaly/dynamodb-toolbox/blob/09ddf4f144c3119802f44119060138ca5183b46e/src/lib/utils.ts#L45).
Encountered this when upgrading a TS codebase to `v0.3` from `v0.2` which uses transforms a fair amount. All my tests passed with this change, and the code wouldn't compile without it.
> Fix type of transform entity config

- src/classes/Entity/Entity.ts
- src/classes/Table/Table.ts
- src/lib/parseCompositeKey.ts
- src/lib/parseEntity.ts
- src/lib/parseTable.ts
- src/lib/validateTypes.ts
This was a problem because `typeof null === 'object'`. In particular this was causing issues with `default: null` on list fields.
Reference: https://stackoverflow.com/questions/8834126/how-to-efficiently-check-if-variable-is-array-or-object-in-nodejs-v8
> fix: corrected "object but not array"-checks

- src/__tests__/expressionBuilder.unit.test.ts
- src/lib/expressionBuilder.ts
Fixes #214 by allowing nested `attr` paths (dot notation) for `exists` conditions.
e.g. currently this:
```js
{
conditions: {
attr: 'a.b.c',
exists: true
}
}
```
Generates this (which doesn't work):
```js
{
ExpressionAttributeNames: {
'#attr1': 'a.b.c'
},
ConditionExpression: 'attribute_exists(#attr_1)'
}
```
With this PR, it will instead generate this (which does work):
```js
{
ExpressionAttributeNames: {
'#attr1_0': 'a',
'#attr1_1': 'b',
'#attr1_2': 'c'
},
ConditionExpression: 'attribute_exists(#attr_1_0.#attr_1_1.#attr_1_2)'
}
```
The [AWS docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html) suggest that `attribute_exists(a.b.c)` should work but it doesn't, at least not via the JS SDK. I found out about the above syntax and …
> Allow nested attr paths (dot notation) for exists conditions

- src/__tests__/expressionBuilder.unit.test.ts
- src/lib/expressionBuilder.ts
Further to #288 - adds support (and tests) for nested `attr` and `size` paths (dot notation) for all other condition/operator types, i.e. `eq`, `ne`, `in`, `between` and so on.
> Allow nested attr/size path (dot notation) for all condition types

- docs/docs/type-inference/index.md
- src/__tests__/type-infering.unit.test.ts
- src/classes/Entity/Entity.ts
- src/classes/Entity/types.ts
- src/lib/parseEntity.ts
- src/lib/utils.ts
Fixes https://github.com/jeremydaly/dynamodb-toolbox/issues/246
This is breaking as `Name` generic type now becomes the first generic type. Developers using `Overlays` have to update their code to follow the change.
It was needed to detect if we are using an instance (`Name` is a narrow string like `"MyEntityName"`) or the general `Entity` type (`Name` is simply `string`) in the rest of the type computations.
I updated the documentation and tests as well.
The first commit is a simple formatting by prettier, no logic has been modified.
There are 2 small regressions, that were needed otherwise TS was going crazy:
- `Aliases` are not prevented from attribute keys anymore (`{ entity: { type: "string" } }` doesn't raise a type error)
- `myEntity.sortKey` is not hardly typed (it returns `null | …
> [BREAKING] Make entities extend default entity type

- .github/workflows/pull-request.yml
- package-lock.json
- package.json
- src/lib/parseEntity.ts
- test-d/index.test-d.ts
- tsconfig.build.json
- tsconfig.json
This fixes the issue reported in #269.
In the first commit I add a command that runs [tsd](https://github.com/SamVerschueren/tsd) to test the generated declaration files. Running `npm run test-types` then fails with the output:
<blockquote>
<pre>dist/lib/parseEntity.d.ts:22:20
✖  22:20  Type alias ParsedEntity circularly references itself.
1 error</pre>
</blockquote>
The typescript type checker is fairly permissive of cyclical references in the types it has inferred from objects and functions, but it becomes problematic in `dist` because in the generated declaration file there is a circular reference between `addEntity` on `Table` and `ParsedEntity`, due to the declared return type of `parseEntity`.
The issue can be fixed if we don't use `ReturnType<typeof parseEntity>` but instead …
> fix: typescript errors in built declaration types

- src/v1/item/typers/any/interface.ts
- src/v1/item/typers/any/options.ts
- src/v1/item/typers/any/typer.ts
- src/v1/item/typers/any/typer.unit.test.ts
- src/v1/item/typers/constants/requiredOptions.ts
- src/v1/item/typers/leaf/interface.ts
- src/v1/item/typers/leaf/options.ts
- src/v1/item/typers/leaf/typer.ts
- src/v1/item/typers/leaf/typer.unit.test.ts
- src/v1/item/typers/list/interface.ts
- src/v1/item/typers/list/options.ts
- src/v1/item/typers/list/typer.ts
- src/v1/item/typers/list/typer.unit.test.ts
- src/v1/item/typers/list/validate.ts
- src/v1/item/typers/map/interface.ts
- src/v1/item/typers/map/options.ts
- src/v1/item/typers/map/typer.ts
- src/v1/item/typers/map/typer.unit.test.ts
- src/v1/playground/entity.ts
Follows a feedback from @jeremydaly to use strings instead of symbols for more simplicity (avoir importing symbols from `"dynamodb-toolbox"`).
> Use strings instead of symbols for required options

- README.md
The link to Alex Debrie's blog post has the square brackets and parentheses transposed, so it rendered incorrectly. This fixes the format so the link is rendered properly.
> fix(README): resolve wrong MD link format

- package-lock.json
- package.json
- src/__tests__/entity.put.unit.test.ts
- src/__tests__/type-infering.unit.test.ts
- src/classes/Entity/Entity.ts
- src/classes/Entity/types.ts
- src/classes/Table/Table.ts
- src/lib/utils.ts
PR to upgrade ts-toolbelt to 9.6.0 (using v6 causes a bug on my project, so here I am).
There some format changes because I use prettier and didn't save formatting corrections in a separate commit 😔
Notable changes:
- I updated `If` because `B.True` and `B.False` are not available anymore
- I created a small `Compute` type generic because the one from `ts-toolbelt` is bugged
- I replaced `C.PromiseOf` to `A.Await` (upgrade breaking change)
Otherwise, works fine !
> chore(deps): upgrade ts-toolbelt to 9.6.0

- package.json
It seems we're missing a constants file in the files array causing issues when installing with yarn v2.
When I imported this package the `.dist` folder would not contain `constants.js` and `constants.d.ts` which breaks the whole module.
> fix: resolve missing constants file in dist

- src/__tests__/validateTypes.unit.test.ts
- src/lib/validateTypes.ts
Hey :wave:
closes #78.
Hope ya'll enjoying your weekend! 🍻
> fix(lib/validateTypes): `{ type: 'number', coerce: true }` & `'123.00'` shouldn't throw.

- src/__tests__/entity.put.unit.test.ts
- src/classes/Entity/Entity.ts
- Validate type function is called before transform function. It allows user to do anything in transform including return invalid values.
- Transform receives abridged value not the one supplied by user due to alterations by validateType
Validate value type after transform. Also fixes #299 and similar issues. 
Transform is supposed to receive (value, data) as arguments where value is supplied value not after type conversions like string to number. ValidateType function does this and various similar conversions for flexibility.
> fix(entity)!: validate value after applying transform

- README.md
- docs/docs/introduction/quick-start.md
- Changes documentation for docusaurus with more information on aws-sdk v2
- Also changes some documentation for Readme.md for this github repo
closes #374
> docs: add AWS SDK v2 installation instructions

- src/__tests__/parse-alias.unit.test.ts
- src/lib/parseMapping.ts
[Original Issue](https://github.com/jeremydaly/dynamodb-toolbox/issues/85)
* Fix by allow check alias name is same to the field name.
> fix(lib/parseMapping): resolve alias check error on same field

- src/__tests__/entity.update.unit.test.ts
- src/classes/Entity/Entity.ts
> fix(entity): resolve removal of empty arrays when removeNulls is true

- README.md
- update quick start for aws-sdk v3
- update `DocumentClient SDK Reference` link to v3
- remove `we're using aws-sdk v2` notice
> docs(README): update quick start to aws-sdk v3

- docs/docs/table/methods.md
The request limit was increased in September 2022. https://aws.amazon.com/about-aws/whats-new/2022/09/amazon-dynamodb-supports-100-actions-per-transaction/
closes #479
> docs: update transacWrite request limit

- src/__tests__/formatItem.unit.test.ts
- src/lib/formatItem.ts
> fix: resolve null attributes being wrapped when parsed

- src/__tests__/entity.update.unit.test.ts
- src/classes/Entity/Entity.ts
There is a bug with attributes that are mapped and use a default value.  
The issue is that you cannot update the field once it's initially set, because the code is looking for the key and not the alias.
ex. 
```js
{ type: 'number', map: 'test_mapped_number', default: 0, onUpdate: false }
```
This fixes this issue.
> Fix issue with mapped fields and defaults on update

- docs/docs/introduction/quick-start.md
- docs/docs/introduction/what-is-dynamodb-toolbox.md
Currently, the installation guide only includes that for aws-sdk v2, with aws-sdk v2 soon to go into maintenance mode, we should update the installation guide to also include aws-sdk v3 as the recommended.
This PR also fixed duplicate imports from `'@aws-sdk/client-dynamodb'`.
Please let me know your thoughts.
> doc: update installation guide for aws v3

- src/__tests__/entity.put.unit.test.ts
- src/__tests__/validateTypes.unit.test.ts
- src/lib/validateTypes.ts
Fix #592
Attribute definitions should _never_ be mutated, as this will result in changing the data types returned by future reads, and potentially cause catastrophic loss of precision. This PR removes the mutating code.
> fix(lib/validate-types): resolve attr type changed to number when using bigint

- package.json
Fixes #612 
Webpack requires when using conditional exports that `default` property is the last one in the `exports` property. This resolves that issue.
> fix: make default prop the last in exports

- package.json
Node.js uses either file extensions or the `"type"` field in `package.json` to determine if files are CommonJS or ES Module files. When we shipped dual module support, `package.json` files were placed in both `dist/esm` and `dist/cjs` with the correct `"type"` property. This would enable consumers of the library to correctly interpret what type of module system the files were using. 
The problem is that we did not add these `dist` specific sub `package.json` files to the `files` property of the root `package.json` so they were never published. This led to Node assuming all files were ESM, even the ones in `dist/cjs`.
This leads to errors for folks trying to use CommonJs. This PR adds those files into the `files` property to resolve this issue.
Resolves #615
> fix: add dist package.json to files

- src/index.ts
fixes #631
I have also encountered this issue (Typescript error: TS2742) while converting a data access module I have to Typescript. This module is an NPM dependency in other repos, so I need the typescript definitions files.
My grasp on Typescript is a little tenuous, But from all that I could read and gather from similar issues and actions taken in other libraries, it seems that exporting the additional types is necessary. 
As far as I can see the only additional type needed in the end was `ParseAttributes`, This addition has allowed me to build my project with Typescript and use it. 
Existing tests continue to pass. I can't see any other side effects, but please let me know if there is another approach or if this change is undesirable.
A minimal repo demonstrating the issue: …
> Add missing type: ParseAttributes, to satisfy esm typescript build issue in consuming project

- src/__tests__/normalizeData.unit.test.ts
- src/lib/normalizeData.ts
Proposed solution for : https://github.com/jeremydaly/dynamodb-toolbox/issues/739
Isolate key check to table Partition Key and Sort Keys only
> Don't throw for undefined dependsOn attributes in Index key fields

- docs/docs/6-v0/3-entity/3-methods.md
Figuring this out took me way longer than I'd like to admit so I've added a simple example on how to remove a nested attribute from a map.. 😉
Also, this seems to work regardless of the `removeNullAttributes` table property state - it removes the attribute even if it's set to `false`
> Document removing nested attribute from a 'map'

- tsconfig.esm.json
Corrects the build configuration to properly output ESM format for the ESM build target,
instead of incorrectly generating CommonJS modules.
ref: https://cdn.jsdelivr.net/npm/dynamodb-toolbox@1.0.0/dist/esm/attributes/string/index.js
> fix: esm build output

- docs/src/css/custom.css
- docs/src/pages/index.tsx
I was browsing through the docs and saw this visual bug on mobile, here's the fix 😊
Go to https://www.dynamodbtoolbox.com/ on mobile and scroll to the bottom to see the bug
> fix(docs): horizontal overflow on mobile

- src/attributes/list/typer.ts
- src/attributes/record/typer.ts
- src/attributes/set/typer.ts
A very small one to clarify some type documentation (`record`, `set` and `list`).
The documentation now says
```
* Note that record keys and elements have constraints. They must be:
* - Required (required: AtLeastOnce)
* - Displayed (hidden: false)
* - Not key (key: false)
* - Not renamed (savedAs: undefined)
* - Not defaulted (defaults: undefined)
```
I'm not sure I understand that fully. The constraint "must be" hidden=false, but I can do this
```typescript
attr: record(string(), number(), { hidden: true })
```
and the [docs here](https://www.dynamodbtoolbox.com/docs/schemas/record#required) say
In any case this PR avoids some confusion I got while reading the type doc :)
Thanks again for this amazing lib guys :snowman:
> Type documentation clarification: 'Note' instead of 'Not'

- docs/docs/4-schemas/4-custom-validation/index.md
The example here is incorrectly passing a string instead of an object: https://www.dynamodbtoolbox.com/docs/schemas/custom-validation#validators
> fix custom validation example

- docs/docs/3-entities/4-actions/14-transact-delete/index.md
- docs/docs/3-entities/4-actions/9-batch-delete/index.md
Minor patch to this sentence: "Contrary to DeleteItemCommand**S** (no _-s_ here), batch deletes cannot be conditioned, nor return the values of the deleted items."
> fix: DeleteItemCommands -> DeleteItemCommand in docs

- src/schema/types/paths.ts
- src/schema/types/paths.type.test.ts
Add unions to the `AnySchemaPath` to allow autocomplete and enhance follow-up of that type by enforcing the use of a `.` or a `[` (which are the key selectors in Javascript)
Resolves #1163
> feat: 🏷️ add type completition and add strict matching after the schema path
